In [1]:
from pandas import read_csv, DataFrame
from numpy import arange
import numpy as np
import os 
path_to_data = '/mmfs1/gscratch/amath/dob1998/emissions_forecasting/data/grouped_data/'

years = arange(1995,2023)

## In this notebook we evaluate trends in the grouped data. Below are categorizations of the different products found in the data.

### Lowest Level Aggregation

In [2]:
agg3_indxs = [0,19,31,42,54,63,75,84,85,87,89,92,95,103,115,116,123,127,139,141,146,149,151,175,182,185,187,189,195,200]
agg3_names = ['Farming and agriculture', 'Primary fossil fuels', 'Ores and minerals', 'Food products and tobacco', 'Fabric and paper products', 'Secondary fossil fuels', 
'Petroleum products', 'Nuclear fuel', 'Plastics', 'Fetilisers', 'Chemicals, charcoal, and additives/blenders', 'Biofuels', 'Non-metallic mineral products', 'Metals and alloys',
'Foundry work services', 'Metal products', 'Furniture and other goods n.e.c., raw materials, and bottles', 'Electricity', 'Electricity services', 'Other gas types', 'Water services',
'Construction rervices and recycling', 'Trade and services', 'Incineration', 'Biogasification and land application', 'Composting and land application', 'Waste water treatment',
'Landfill', 'Other services and households with employees']

In [10]:
agg3 = []
for i in range(len(agg3_names)):
    agg3 = agg3 + [agg3_names[i]] * (agg3_indxs[i+1] - agg3_indxs[i])

Farming and Agriculture:                            0-18

Primary Fossil Fuels:                               19-30

Ores and Minerals:                                  31-41

Food Products and Tobacco:                          42-53

Fabric and Paper Products:                          54-62   

Secondary Fossil Fuels:                             63-74

Petroleum Products:                                 75-83

Nuclear Fuel:                                       84

Plastics:                                           85-86

Fertilisers:                                        87-88

Chemicals, charcoal, and additives/blenders         89-91

Biofuels:                                           92-94

Non-Metallic Mineral Products:                      95-102

Metals and Alloys:                                  103-114

Foundry Work Services:                              115

Metal Products:                                     116-122

Furniture, Raw Materials, and Bottles:              123-126

Electricity Types:                                  127-138

Electricity Services:                               139-140

Other Gas Types:                                    141-145

Water Services:                                     146-148

Construction Services and Recycling:                149-150

Trade and Services:                                 151-174

Incineration:                                       175-181

Biogasification and Land Application:               182-184

Composting and Land Application:                    185-186

Waste Water Treatment:                              187-188

Landfill:                                           189-194

Other Services and Households with Employees:       195-199

In [27]:
v1 = ['A', 'B', 'C']
v2 = [1, 2, [3,4]]

# for el in zip(v1,v2):
#     print(el[0])

len(v1)
temp = 4 * v2

In [30]:
v = np.array([1,2,3,4])
v[[0,2]]

array([1, 3])

In [5]:
import numpy as np
# print(np.arange(1,5))
# for entry in dict:
#     print(entry)

In [6]:
v = np.empty(10, dtype='<U5')

In [7]:
v[0] = 'hello'

In [8]:
type(v)

numpy.ndarray

## Viewing changes in energy sources over time

In [3]:
fossil_fuels = np.concatenate((arange(19,31), arange(63,75), arange(141,146)))
electricity = np.arange(127,141)

In [4]:
Zs = []
xs = []
Ys = []
Fs = []
F_Ys = []
D_cbas = []
D_pbas = []

for year in years:
    Z = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/Z.csv', header = 0, index_col = 0)
    x = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/x.csv', index_col = 0)
    Y = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/Y.csv', header = 0, index_col = 0)
    F = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/F.csv', header = 0, index_col = 0)
    F_Y = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/F_Y.csv', header = 0, index_col = 0)
    D_cba = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/D_cba.csv', header = 0, index_col = 0)
    D_pba = read_csv(path_to_data + 'IOT_' + str(year) + '_pxp/D_pba.csv', header = 0, index_col = 0)

    Zs.append(Z)
    xs.append(x)
    Ys.append(Y)
    Fs.append(F)
    F_Ys.append(F_Y)
    D_cbas.append(D_cba)
    D_pbas.append(D_pba)

In [7]:
temp = DataFrame(columns = years)

In [8]:
Zs[0].iloc[:,120]

sector
Paddy rice                                             4.020943
Wheat                                                 13.184613
Cereal grains nec                                      9.361226
Vegetables, fruit, nuts                                9.724200
Oil seeds                                             10.010081
                                                        ...    
Membership organisation services n.e.c. (91)         446.417136
Recreational, cultural and sporting services (92)    301.577351
Other services (93)                                  847.532722
Private households with employed persons (95)         10.104079
Extra-territorial organizations and bodies             0.000000
Name: Radio, television and communication equipment and apparatus (32), Length: 200, dtype: float64

In [9]:
for i in range(0,28):
    temp.iloc[:,i] = Zs[i].iloc[:,120]

In [34]:
temp2 = temp.iloc[np.concatenate((fossil_fuels, electricity))]
temp3 = temp2.sort_values(by = [1995],ascending = False)
temp3

1995         1996  \
sector                                                                         
Electricity by coal                                 1608.269617  1591.342607   
Electricity by nuclear                              1344.880295  1274.868025   
Electricity by gas                                  1123.262234  1075.768902   
Distribution and trade services of electricity       914.691472   883.832297   
Electricity by petroleum and other oil derivatives   697.810715   166.540345   
Transmission services of electricity                 615.316416   369.423337   
Electricity by hydro                                 416.054522    288.21308   
Motor Gasoline                                       188.737739   204.818277   
Heavy Fuel Oil                                       183.954274   292.315934   
Gas/Diesel Oil                                       162.474867   186.740277   
Liquefied Petroleum Gases (LPG)                      104.862728   102.282324   
Electricity by biomass and waste                      84.457670    46.750828   
Coke Oven Coke                                        31.257436    47.898717   
Crude petroleum and services related to crude o...    25.140291    23.239068   
Kerosene                                              22.984598    26.582282   
Electricity nec                                       22.103008    18.717656   
Other Bituminous Coal                                 15.630587    21.161679   
Electricity by Geothermal                             12.733500    13.609972   
Coke oven gas                                         10.822525     8.709927   
Kerosene Type Jet Fuel                                 7.218484      8.00545   
Coking Coal                                            5.937432     6.977449   
Blast Furnace Gas                                      4.220398    13.869257   
Biogas                                                 3.076502     1.680112   
Gas Works Gas                                          2.828406     2.185247   
Natural gas and services related to natural gas...     2.205734     7.332961   
Lignite/Brown Coal                                     2.052480     4.304687   
Natural Gas Liquids                                    1.711140     2.008535   
Electricity by wind                                    1.143876     1.375463   
Sub-Bituminous Coal                                    0.930015     1.142717   
Anthracite                                             0.811510     4.888705   
BKB/Peat Briquettes                                    0.682054     1.166494   
Other Hydrocarbons                                     0.448833     0.476373   
Electricity by solar thermal                           0.173955     0.191907   
Oxygen Steel Furnace Gas                               0.168472     0.035413   
Peat                                                   0.139880     0.029228   
Electricity by solar photovoltaic                      0.138146     0.178133   
Refinery Gas                                           0.082329     0.059168   
Coal Tar                                               0.050513     0.062885   
Electricity by tide, wave, ocean                       0.048869     0.035516   
Patent Fuel                                            0.041511     0.048587   
Aviation Gasoline                                      0.033114     0.032086   
Gasoline Type Jet Fuel                                 0.016129     0.013958   
Gas Coke                                               0.000066     0.000079   

                                                           1997         1998  \
sector                                                                         
Electricity by coal                                 1871.396726  1982.268456   
Electricity by nuclear                              1494.076734  1602.443762   
Electricity by gas                                  1263.305223  1244.541619   
Distribution and trade services of electricity      1025.4

In [13]:
electricity


array([127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140])

In [14]:
fossil_fuels

array([ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  63,
        64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74, 141, 142,
       143, 144, 145])

In [27]:
df = DataFrame({
    'col1': ['A', 'A', 'B', np.nan, 'D', 'C'],
    'col2': [2, 1, 9, 8, 7, 4],
    'col3': [0, 1, 9, 4, 2, 3],
    'col4': ['a', 'B', 'c', 'D', 'e', 'F']
})

In [28]:
df

col1  col2  col3 col4
0    A     2     0    a
1    A     1     1    B
2    B     9     9    c
3  NaN     8     4    D
4    D     7     2    e
5    C     4     3    F

In [31]:
df.sort_values(by=['col2'], ascending=True)

col1  col2  col3 col4
1    A     1     1    B
0    A     2     0    a
5    C     4     3    F
4    D     7     2    e
3  NaN     8     4    D
2    B     9     9    c